//
// ContactEmailCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContactEmailCreateDto: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var timestamp: Date?
    public var contactId: String?
    public var address: String?
    public var label: String?
    public var isPrimary: Bool?

    public init(id: UUID? = nil, timestamp: Date? = nil, contactId: String? = nil, address: String? = nil, label: String? = nil, isPrimary: Bool? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.contactId = contactId
        self.address = address
        self.label = label
        self.isPrimary = isPrimary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case contactId
        case address
        case label
        case isPrimary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(contactId, forKey: .contactId)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
    }
}

