//
// PaymentProviderRegistrationsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PaymentProviderRegistrationsAPI {

    /**
     Provisions a provider webhook registration
     
     - parameter tenantId: (query)  
     - parameter createProviderWebhookRegistrationRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createAsync(tenantId: UUID, createProviderWebhookRegistrationRequest: CreateProviderWebhookRegistrationRequest? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ProviderWebhookRegistrationCreatedDtoEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return createAsyncWithRequestBuilder(tenantId: tenantId, createProviderWebhookRegistrationRequest: createProviderWebhookRegistrationRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Provisions a provider webhook registration
     - POST /api/v2/PaymentsService/PaymentProviderRegistrations
     - Stores the BYO signing secret in the tenant options store, creates + activates the registration, and reveals the one-time plaintext webhook key plus its fully-composed inbound URL.
     - parameter tenantId: (query)  
     - parameter createProviderWebhookRegistrationRequest: (body)  (optional)
     - returns: RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope> 
     */
    open class func createAsyncWithRequestBuilder(tenantId: UUID, createProviderWebhookRegistrationRequest: CreateProviderWebhookRegistrationRequest? = nil) -> RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope> {
        let localVariablePath = "/api/v2/PaymentsService/PaymentProviderRegistrations"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createProviderWebhookRegistrationRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Lists the tenant's provider registrations
     
     - parameter tenantId: (query)  
     - parameter paymentProviderRegistrationDtoCollectionQueryParameters: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getAsync(tenantId: UUID, paymentProviderRegistrationDtoCollectionQueryParameters: PaymentProviderRegistrationDtoCollectionQueryParameters? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: PaymentProviderRegistrationDtoListEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return getAsyncWithRequestBuilder(tenantId: tenantId, paymentProviderRegistrationDtoCollectionQueryParameters: paymentProviderRegistrationDtoCollectionQueryParameters).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Lists the tenant's provider registrations
     - GET /api/v2/PaymentsService/PaymentProviderRegistrations
     - Gets all provider registrations for the current tenant with OData support (no secret is ever returned).
     - parameter tenantId: (query)  
     - parameter paymentProviderRegistrationDtoCollectionQueryParameters: (body)  (optional)
     - returns: RequestBuilder<PaymentProviderRegistrationDtoListEnvelope> 
     */
    open class func getAsyncWithRequestBuilder(tenantId: UUID, paymentProviderRegistrationDtoCollectionQueryParameters: PaymentProviderRegistrationDtoCollectionQueryParameters? = nil) -> RequestBuilder<PaymentProviderRegistrationDtoListEnvelope> {
        let localVariablePath = "/api/v2/PaymentsService/PaymentProviderRegistrations"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: paymentProviderRegistrationDtoCollectionQueryParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaymentProviderRegistrationDtoListEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Counts the tenant's provider registrations
     
     - parameter tenantId: (query)  
     - parameter paymentProviderRegistrationDtoCollectionQueryParameters: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCountAsync(tenantId: UUID, paymentProviderRegistrationDtoCollectionQueryParameters: PaymentProviderRegistrationDtoCollectionQueryParameters? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Int32Envelope?, _ error: Error?) -> Void)) -> RequestTask {
        return getCountAsyncWithRequestBuilder(tenantId: tenantId, paymentProviderRegistrationDtoCollectionQueryParameters: paymentProviderRegistrationDtoCollectionQueryParameters).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Counts the tenant's provider registrations
     - GET /api/v2/PaymentsService/PaymentProviderRegistrations/Count
     - Gets the count of provider registrations for the current tenant (OData sibling of the list).
     - parameter tenantId: (query)  
     - parameter paymentProviderRegistrationDtoCollectionQueryParameters: (body)  (optional)
     - returns: RequestBuilder<Int32Envelope> 
     */
    open class func getCountAsyncWithRequestBuilder(tenantId: UUID, paymentProviderRegistrationDtoCollectionQueryParameters: PaymentProviderRegistrationDtoCollectionQueryParameters? = nil) -> RequestBuilder<Int32Envelope> {
        let localVariablePath = "/api/v2/PaymentsService/PaymentProviderRegistrations/Count"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: paymentProviderRegistrationDtoCollectionQueryParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Int32Envelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Rotates a registration's webhook key
     
     - parameter tenantId: (query)  
     - parameter registrationId: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func rotateKeyAsync(tenantId: UUID, registrationId: UUID, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ProviderWebhookRegistrationCreatedDtoEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return rotateKeyAsyncWithRequestBuilder(tenantId: tenantId, registrationId: registrationId).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Rotates a registration's webhook key
     - POST /api/v2/PaymentsService/PaymentProviderRegistrations/{registrationId}/RotateKey
     - Mints a fresh webhook key (invalidating the previous one) and reveals it once, plus its composed URL.
     - parameter tenantId: (query)  
     - parameter registrationId: (path)  
     - returns: RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope> 
     */
    open class func rotateKeyAsyncWithRequestBuilder(tenantId: UUID, registrationId: UUID) -> RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope> {
        var localVariablePath = "/api/v2/PaymentsService/PaymentProviderRegistrations/{registrationId}/RotateKey"
        let registrationIdPreEscape = "\(APIHelper.mapValueToPathItem(registrationId))"
        let registrationIdPostEscape = registrationIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{registrationId}", with: registrationIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ProviderWebhookRegistrationCreatedDtoEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
