//
// TrustSigningReadinessDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TrustSigningReadinessDto: Codable, JSONEncodable, Hashable {

    public enum ExpectedSignatureFormat: String, Codable, CaseIterable {
        case unknown = "Unknown"
        case xades = "XAdES"
        case pades = "PAdES"
        case cades = "CAdES"
        case smime = "SMIME"
        case detachedXmlDSig = "DetachedXmlDSig"
        case enveloped = "Enveloped"
        case other = "Other"
    }
    public enum ExpectedSignaturePurpose: String, Codable, CaseIterable {
        case unknown = "Unknown"
        case regulatorySubmission = "RegulatorySubmission"
        case contractExecution = "ContractExecution"
        case emailSigning = "EmailSigning"
        case internalApproval = "InternalApproval"
        case evidenceSealing = "EvidenceSealing"
        case agentCredential = "AgentCredential"
        case other = "Other"
    }
    public var canProceed: Bool?
    public var blockingReasons: [String]?
    public var warnings: [String]?
    public var resolvedDocumentTitle: String?
    public var resolvedProfileDisplayName: String?
    public var resolvedCertificateTitle: String?
    public var expectedSignatureFormat: ExpectedSignatureFormat?
    public var expectedSignaturePurpose: ExpectedSignaturePurpose?
    public var expectedDigestAlgorithm: String?
    public var expectedSignatureAlgorithm: String?
    public var expectedCanonicalizationAlgorithm: String?
    public var policyIdentifier: String?
    public var authorityProfile: String?
    public var requiresCustodyProvider: Bool?
    public var requiresSourceArtifact: Bool?
    public var requiresCertificate: Bool?
    public var correlationId: String?

    public init(canProceed: Bool? = nil, blockingReasons: [String]? = nil, warnings: [String]? = nil, resolvedDocumentTitle: String? = nil, resolvedProfileDisplayName: String? = nil, resolvedCertificateTitle: String? = nil, expectedSignatureFormat: ExpectedSignatureFormat? = nil, expectedSignaturePurpose: ExpectedSignaturePurpose? = nil, expectedDigestAlgorithm: String? = nil, expectedSignatureAlgorithm: String? = nil, expectedCanonicalizationAlgorithm: String? = nil, policyIdentifier: String? = nil, authorityProfile: String? = nil, requiresCustodyProvider: Bool? = nil, requiresSourceArtifact: Bool? = nil, requiresCertificate: Bool? = nil, correlationId: String? = nil) {
        self.canProceed = canProceed
        self.blockingReasons = blockingReasons
        self.warnings = warnings
        self.resolvedDocumentTitle = resolvedDocumentTitle
        self.resolvedProfileDisplayName = resolvedProfileDisplayName
        self.resolvedCertificateTitle = resolvedCertificateTitle
        self.expectedSignatureFormat = expectedSignatureFormat
        self.expectedSignaturePurpose = expectedSignaturePurpose
        self.expectedDigestAlgorithm = expectedDigestAlgorithm
        self.expectedSignatureAlgorithm = expectedSignatureAlgorithm
        self.expectedCanonicalizationAlgorithm = expectedCanonicalizationAlgorithm
        self.policyIdentifier = policyIdentifier
        self.authorityProfile = authorityProfile
        self.requiresCustodyProvider = requiresCustodyProvider
        self.requiresSourceArtifact = requiresSourceArtifact
        self.requiresCertificate = requiresCertificate
        self.correlationId = correlationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canProceed
        case blockingReasons
        case warnings
        case resolvedDocumentTitle
        case resolvedProfileDisplayName
        case resolvedCertificateTitle
        case expectedSignatureFormat
        case expectedSignaturePurpose
        case expectedDigestAlgorithm
        case expectedSignatureAlgorithm
        case expectedCanonicalizationAlgorithm
        case policyIdentifier
        case authorityProfile
        case requiresCustodyProvider
        case requiresSourceArtifact
        case requiresCertificate
        case correlationId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(canProceed, forKey: .canProceed)
        try container.encodeIfPresent(blockingReasons, forKey: .blockingReasons)
        try container.encodeIfPresent(warnings, forKey: .warnings)
        try container.encodeIfPresent(resolvedDocumentTitle, forKey: .resolvedDocumentTitle)
        try container.encodeIfPresent(resolvedProfileDisplayName, forKey: .resolvedProfileDisplayName)
        try container.encodeIfPresent(resolvedCertificateTitle, forKey: .resolvedCertificateTitle)
        try container.encodeIfPresent(expectedSignatureFormat, forKey: .expectedSignatureFormat)
        try container.encodeIfPresent(expectedSignaturePurpose, forKey: .expectedSignaturePurpose)
        try container.encodeIfPresent(expectedDigestAlgorithm, forKey: .expectedDigestAlgorithm)
        try container.encodeIfPresent(expectedSignatureAlgorithm, forKey: .expectedSignatureAlgorithm)
        try container.encodeIfPresent(expectedCanonicalizationAlgorithm, forKey: .expectedCanonicalizationAlgorithm)
        try container.encodeIfPresent(policyIdentifier, forKey: .policyIdentifier)
        try container.encodeIfPresent(authorityProfile, forKey: .authorityProfile)
        try container.encodeIfPresent(requiresCustodyProvider, forKey: .requiresCustodyProvider)
        try container.encodeIfPresent(requiresSourceArtifact, forKey: .requiresSourceArtifact)
        try container.encodeIfPresent(requiresCertificate, forKey: .requiresCertificate)
        try container.encodeIfPresent(correlationId, forKey: .correlationId)
    }
}

