//
// PrivateMessageUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PrivateMessageUpdateDto: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var message: String?

    public init(title: String? = nil, message: String? = nil) {
        self.title = title
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

