//
// AccountRelationCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountRelationCreateDto: Codable, JSONEncodable, Hashable {

    static let accountIdRule = StringRule(minLength: 0, maxLength: 36, pattern: nil)
    public var id: UUID?
    public var timestamp: Date?
    public var accountId: String?

    public init(id: UUID? = nil, timestamp: Date? = nil, accountId: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.accountId = accountId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case accountId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(accountId, forKey: .accountId)
    }
}

