//
// FiscalResponsibilityRecordDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FiscalResponsibilityRecordDto: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var fiscalResponsibilityId: String?
    public var billingProfileId: String?
    public var tenantId: String?
    public var enrollmentId: String?

    public init(id: String? = nil, timestamp: Date? = nil, fiscalResponsibilityId: String? = nil, billingProfileId: String? = nil, tenantId: String? = nil, enrollmentId: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.fiscalResponsibilityId = fiscalResponsibilityId
        self.billingProfileId = billingProfileId
        self.tenantId = tenantId
        self.enrollmentId = enrollmentId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case fiscalResponsibilityId
        case billingProfileId
        case tenantId
        case enrollmentId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(fiscalResponsibilityId, forKey: .fiscalResponsibilityId)
        try container.encodeIfPresent(billingProfileId, forKey: .billingProfileId)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(enrollmentId, forKey: .enrollmentId)
    }
}

