//
// FiscalYearUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FiscalYearUpdateDto: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var closed: Bool?
    public var endDate: Date?
    public var startDate: Date?

    public init(name: String? = nil, description: String? = nil, closed: Bool? = nil, endDate: Date? = nil, startDate: Date? = nil) {
        self.name = name
        self.description = description
        self.closed = closed
        self.endDate = endDate
        self.startDate = startDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case closed
        case endDate
        case startDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(closed, forKey: .closed)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(startDate, forKey: .startDate)
    }
}

