//
// JournalUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JournalUpdateDto: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    static let descriptionRule = StringRule(minLength: 1, maxLength: 1000, pattern: nil)
    static let parentJournalIDRule = StringRule(minLength: 0, maxLength: 36, pattern: nil)
    static let journalTypeIDRule = StringRule(minLength: 0, maxLength: 36, pattern: nil)
    static let ledgerIDRule = StringRule(minLength: 0, maxLength: 36, pattern: nil)
    public var name: String?
    public var description: String?
    public var dateTime: Date?
    public var parentJournalID: String?
    public var journalTypeID: String?
    public var ledgerID: String?

    public init(name: String? = nil, description: String? = nil, dateTime: Date? = nil, parentJournalID: String? = nil, journalTypeID: String? = nil, ledgerID: String? = nil) {
        self.name = name
        self.description = description
        self.dateTime = dateTime
        self.parentJournalID = parentJournalID
        self.journalTypeID = journalTypeID
        self.ledgerID = ledgerID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case dateTime
        case parentJournalID
        case journalTypeID
        case ledgerID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(dateTime, forKey: .dateTime)
        try container.encodeIfPresent(parentJournalID, forKey: .parentJournalID)
        try container.encodeIfPresent(journalTypeID, forKey: .journalTypeID)
        try container.encodeIfPresent(ledgerID, forKey: .ledgerID)
    }
}

