//
// CourseTeamMembershipCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CourseTeamMembershipCreateDto: Codable, JSONEncodable, Hashable {

    public enum CourseTeamMembershipType: String, Codable, CaseIterable {
        case admin = "Admin"
        case staff = "Staff"
    }
    static let courseIDRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let instructorProfileIDRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: UUID?
    public var timestamp: Date?
    public var courseID: String
    public var instructorProfileID: String
    public var courseTeamMembershipType: CourseTeamMembershipType?

    public init(id: UUID? = nil, timestamp: Date? = nil, courseID: String, instructorProfileID: String, courseTeamMembershipType: CourseTeamMembershipType? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.courseID = courseID
        self.instructorProfileID = instructorProfileID
        self.courseTeamMembershipType = courseTeamMembershipType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case courseID
        case instructorProfileID
        case courseTeamMembershipType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encode(courseID, forKey: .courseID)
        try container.encode(instructorProfileID, forKey: .instructorProfileID)
        try container.encodeIfPresent(courseTeamMembershipType, forKey: .courseTeamMembershipType)
    }
}

