//
// CourseEnrollmentUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CourseEnrollmentUpdateDto: Codable, JSONEncodable, Hashable {

    public var courseCohortId: String?
    public var courseCompletionCertificateId: String?

    public init(courseCohortId: String? = nil, courseCompletionCertificateId: String? = nil) {
        self.courseCohortId = courseCohortId
        self.courseCompletionCertificateId = courseCompletionCertificateId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case courseCohortId
        case courseCompletionCertificateId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(courseCohortId, forKey: .courseCohortId)
        try container.encodeIfPresent(courseCompletionCertificateId, forKey: .courseCompletionCertificateId)
    }
}

