//
// StoreCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StoreCreateDto: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: UUID?
    public var timestamp: Date?
    public var name: String
    public var eCommerce: Bool?
    public var currencyId: String?

    public init(id: UUID? = nil, timestamp: Date? = nil, name: String, eCommerce: Bool? = nil, currencyId: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.name = name
        self.eCommerce = eCommerce
        self.currencyId = currencyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case name
        case eCommerce
        case currencyId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(eCommerce, forKey: .eCommerce)
        try container.encodeIfPresent(currencyId, forKey: .currencyId)
    }
}

