//
// CognitiveAgentVariablesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CognitiveAgentVariablesAPI {

    /**
     Add a variable to a cognitive agent
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableCreateDto: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func createCognitiveAgentVariableAsync(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableCreateDto: CognitiveAgentVariableCreateDto? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return createCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, apiVersion: apiVersion, xApiVersion: xApiVersion, cognitiveAgentVariableCreateDto: cognitiveAgentVariableCreateDto).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Add a variable to a cognitive agent
     - POST /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables
     - Adds a key/value variable to the specified cognitive agent and tenant.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableCreateDto: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func createCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableCreateDto: CognitiveAgentVariableCreateDto? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cognitiveAgentVariableCreateDto)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Remove a variable from a cognitive agent
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func deleteCognitiveAgentVariableAsync(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return deleteCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, id: id, apiVersion: apiVersion, xApiVersion: xApiVersion).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Remove a variable from a cognitive agent
     - DELETE /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}
     - Removes a variable from the specified cognitive agent and tenant.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get a cognitive agent variable by ID
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCognitiveAgentVariableByIdAsync(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: CognitiveAgentVariableDtoEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return getCognitiveAgentVariableByIdAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, id: id, apiVersion: apiVersion, xApiVersion: xApiVersion).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get a cognitive agent variable by ID
     - GET /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}
     - Retrieves a specific variable of a cognitive agent by its identifier.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - returns: RequestBuilder<CognitiveAgentVariableDtoEnvelope> 
     */
    open class func getCognitiveAgentVariableByIdAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil) -> RequestBuilder<CognitiveAgentVariableDtoEnvelope> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CognitiveAgentVariableDtoEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all variables for a cognitive agent
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableDtoCollectionQueryParameters: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCognitiveAgentVariablesAsync(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableDtoCollectionQueryParameters: CognitiveAgentVariableDtoCollectionQueryParameters? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: CognitiveAgentVariableDtoListEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return getCognitiveAgentVariablesAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, apiVersion: apiVersion, xApiVersion: xApiVersion, cognitiveAgentVariableDtoCollectionQueryParameters: cognitiveAgentVariableDtoCollectionQueryParameters).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get all variables for a cognitive agent
     - GET /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables
     - Retrieves all key/value variables for the specified cognitive agent and tenant.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableDtoCollectionQueryParameters: (body)  (optional)
     - returns: RequestBuilder<CognitiveAgentVariableDtoListEnvelope> 
     */
    open class func getCognitiveAgentVariablesAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableDtoCollectionQueryParameters: CognitiveAgentVariableDtoCollectionQueryParameters? = nil) -> RequestBuilder<CognitiveAgentVariableDtoListEnvelope> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cognitiveAgentVariableDtoCollectionQueryParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CognitiveAgentVariableDtoListEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get variable count for a cognitive agent
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableDtoCollectionQueryParameters: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func getCognitiveAgentVariablesCountAsync(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableDtoCollectionQueryParameters: CognitiveAgentVariableDtoCollectionQueryParameters? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Int32Envelope?, _ error: Error?) -> Void)) -> RequestTask {
        return getCognitiveAgentVariablesCountAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, apiVersion: apiVersion, xApiVersion: xApiVersion, cognitiveAgentVariableDtoCollectionQueryParameters: cognitiveAgentVariableDtoCollectionQueryParameters).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get variable count for a cognitive agent
     - GET /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/Count
     - Returns the count of variables for the specified cognitive agent and tenant.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableDtoCollectionQueryParameters: (body)  (optional)
     - returns: RequestBuilder<Int32Envelope> 
     */
    open class func getCognitiveAgentVariablesCountAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableDtoCollectionQueryParameters: CognitiveAgentVariableDtoCollectionQueryParameters? = nil) -> RequestBuilder<Int32Envelope> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/Count"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cognitiveAgentVariableDtoCollectionQueryParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Int32Envelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Update a cognitive agent variable
     
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableUpdateDto: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func updateCognitiveAgentVariableAsync(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableUpdateDto: CognitiveAgentVariableUpdateDto? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Void?, _ error: Error?) -> Void)) -> RequestTask {
        return updateCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: tenantId, agentId: agentId, id: id, apiVersion: apiVersion, xApiVersion: xApiVersion, cognitiveAgentVariableUpdateDto: cognitiveAgentVariableUpdateDto).execute(apiResponseQueue) { result in
            switch result {
            case .success:
                completion((), nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update a cognitive agent variable
     - PUT /api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}
     - Updates the value of a variable for the specified agent and tenant.
     - parameter tenantId: (query)  
     - parameter agentId: (path)  
     - parameter id: (path)  
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter cognitiveAgentVariableUpdateDto: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func updateCognitiveAgentVariableAsyncWithRequestBuilder(tenantId: UUID, agentId: UUID, id: UUID, apiVersion: String? = nil, xApiVersion: String? = nil, cognitiveAgentVariableUpdateDto: CognitiveAgentVariableUpdateDto? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v2/IntelligenceService/CognitiveAgents/{agentId}/Variables/{id}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{agentId}", with: agentIdPostEscape, options: .literal, range: nil)
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: cognitiveAgentVariableUpdateDto)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
