//
// CreateProviderWebhookRegistrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProviderWebhookRegistrationRequest: Codable, JSONEncodable, Hashable {

    public enum CredentialMode: String, Codable, CaseIterable {
        case tenantManaged = "TenantManaged"
        case platformManaged = "PlatformManaged"
        case externalReference = "ExternalReference"
    }
    public var providerCode: String?
    public var externalAccountId: String?
    public var webhookSigningSecret: String?
    public var credentialMode: CredentialMode?

    public init(providerCode: String? = nil, externalAccountId: String? = nil, webhookSigningSecret: String? = nil, credentialMode: CredentialMode? = nil) {
        self.providerCode = providerCode
        self.externalAccountId = externalAccountId
        self.webhookSigningSecret = webhookSigningSecret
        self.credentialMode = credentialMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providerCode
        case externalAccountId
        case webhookSigningSecret
        case credentialMode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(providerCode, forKey: .providerCode)
        try container.encodeIfPresent(externalAccountId, forKey: .externalAccountId)
        try container.encodeIfPresent(webhookSigningSecret, forKey: .webhookSigningSecret)
        try container.encodeIfPresent(credentialMode, forKey: .credentialMode)
    }
}

