//
// PaymentChargebackDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentChargebackDto: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var requestDate: Date?
    public var paymentId: String?
    public var bankProfileId: String?
    public var bankProfileName: String?
    public var totalFees: Double?

    public init(id: String? = nil, timestamp: Date? = nil, requestDate: Date? = nil, paymentId: String? = nil, bankProfileId: String? = nil, bankProfileName: String? = nil, totalFees: Double? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.requestDate = requestDate
        self.paymentId = paymentId
        self.bankProfileId = bankProfileId
        self.bankProfileName = bankProfileName
        self.totalFees = totalFees
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case requestDate
        case paymentId
        case bankProfileId
        case bankProfileName
        case totalFees
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(requestDate, forKey: .requestDate)
        try container.encodeIfPresent(paymentId, forKey: .paymentId)
        try container.encodeIfPresent(bankProfileId, forKey: .bankProfileId)
        try container.encodeIfPresent(bankProfileName, forKey: .bankProfileName)
        try container.encodeIfPresent(totalFees, forKey: .totalFees)
    }
}

