//
// UploadsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UploadsAPI {

    /**
     * enum for parameter publicAccessType
     */
    public enum PublicAccessType_saveFileAsync: String, CaseIterable {
        case _false = "false"
        case container = "Container"
        case blob = "Blob"
        case unknown = "Unknown"
    }

    /**
     * enum for parameter purpose
     */
    public enum Purpose_saveFileAsync: String, CaseIterable {
        case unknown = "Unknown"
        case identityAvatar = "IdentityAvatar"
        case identityBanner = "IdentityBanner"
        case profileAsset = "ProfileAsset"
        case engagementInline = "EngagementInline"
        case engagementAttachment = "EngagementAttachment"
        case messageAttachment = "MessageAttachment"
        case socialPost = "SocialPost"
        case recordAttachment = "RecordAttachment"
        case aiGenerated = "AiGenerated"
        case systemArtifact = "SystemArtifact"
        case temporary = "Temporary"
    }

    /**
     * enum for parameter appFileSource
     */
    public enum AppFileSource_saveFileAsync: String, CaseIterable {
        case unknown = "Unknown"
        case httpUpload = "HttpUpload"
        case integration = "Integration"
        case internalProcess = "InternalProcess"
        case apiClient = "ApiClient"
        case workflowEngine = "WorkflowEngine"
    }

    /**
     Upload a file
     
     - parameter tenantId: (query)  (optional)
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter file: (form)  (optional)
     - parameter notes: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter author: (form)  (optional)
     - parameter isFolder: (form)  (optional)
     - parameter fileName: (form)  (optional)
     - parameter abstract: (form)  (optional)
     - parameter keyWords: (form)  (optional)
     - parameter validResponse: (form)  (optional)
     - parameter parentFileUploadId: (form)  (optional)
     - parameter filePath: (form)  (optional)
     - parameter publicAccessType: (form)  (optional)
     - parameter purpose: (form)  (optional)
     - parameter socialProfileIdValue: (form)  (optional)
     - parameter appFileContent: (form)  (optional)
     - parameter appFileSha256: (form)  (optional)
     - parameter appFileCreatedAtUtc: (form)  (optional)
     - parameter appFileUserIdValue: (form)  (optional)
     - parameter appFileTenantIdValue: (form)  (optional)
     - parameter appFileEnrollmentIdValue: (form)  (optional)
     - parameter appFileSource: (form)  (optional)
     - parameter appFileLength: (form)  (optional)
     - parameter appFileName: (form)  (optional)
     - parameter appFileFileName: (form)  (optional)
     - parameter appFileLastModified: (form)  (optional)
     - parameter appFileSize: (form)  (optional)
     - parameter appFileContentType: (form)  (optional)
     - parameter appFileContentDisposition: (form)  (optional)
     - parameter appFileHeaders: (form)  (optional)
     - parameter id: (form)  (optional)
     - parameter timestamp: (form)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func saveFileAsync(tenantId: UUID? = nil, apiVersion: String? = nil, xApiVersion: String? = nil, file: URL? = nil, notes: String? = nil, title: String? = nil, author: String? = nil, isFolder: Bool? = nil, fileName: String? = nil, abstract: String? = nil, keyWords: String? = nil, validResponse: Bool? = nil, parentFileUploadId: String? = nil, filePath: String? = nil, publicAccessType: PublicAccessType_saveFileAsync? = nil, purpose: Purpose_saveFileAsync? = nil, socialProfileIdValue: UUID? = nil, appFileContent: Data? = nil, appFileSha256: String? = nil, appFileCreatedAtUtc: Date? = nil, appFileUserIdValue: UUID? = nil, appFileTenantIdValue: UUID? = nil, appFileEnrollmentIdValue: UUID? = nil, appFileSource: AppFileSource_saveFileAsync? = nil, appFileLength: Int64? = nil, appFileName: String? = nil, appFileFileName: String? = nil, appFileLastModified: Date? = nil, appFileSize: Int64? = nil, appFileContentType: String? = nil, appFileContentDisposition: String? = nil, appFileHeaders: [String: String]? = nil, id: UUID? = nil, timestamp: Date? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: EmptyEnvelope?, _ error: Error?) -> Void)) -> RequestTask {
        return saveFileAsyncWithRequestBuilder(tenantId: tenantId, apiVersion: apiVersion, xApiVersion: xApiVersion, file: file, notes: notes, title: title, author: author, isFolder: isFolder, fileName: fileName, abstract: abstract, keyWords: keyWords, validResponse: validResponse, parentFileUploadId: parentFileUploadId, filePath: filePath, publicAccessType: publicAccessType, purpose: purpose, socialProfileIdValue: socialProfileIdValue, appFileContent: appFileContent, appFileSha256: appFileSha256, appFileCreatedAtUtc: appFileCreatedAtUtc, appFileUserIdValue: appFileUserIdValue, appFileTenantIdValue: appFileTenantIdValue, appFileEnrollmentIdValue: appFileEnrollmentIdValue, appFileSource: appFileSource, appFileLength: appFileLength, appFileName: appFileName, appFileFileName: appFileFileName, appFileLastModified: appFileLastModified, appFileSize: appFileSize, appFileContentType: appFileContentType, appFileContentDisposition: appFileContentDisposition, appFileHeaders: appFileHeaders, id: id, timestamp: timestamp).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Upload a file
     - POST /api/v2/StorageService/Uploads
     - Uploads a file to tenant or user storage, scanned and catalogued through the storage spine.
     - parameter tenantId: (query)  (optional)
     - parameter apiVersion: (query)  (optional)
     - parameter xApiVersion: (header)  (optional)
     - parameter file: (form)  (optional)
     - parameter notes: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter author: (form)  (optional)
     - parameter isFolder: (form)  (optional)
     - parameter fileName: (form)  (optional)
     - parameter abstract: (form)  (optional)
     - parameter keyWords: (form)  (optional)
     - parameter validResponse: (form)  (optional)
     - parameter parentFileUploadId: (form)  (optional)
     - parameter filePath: (form)  (optional)
     - parameter publicAccessType: (form)  (optional)
     - parameter purpose: (form)  (optional)
     - parameter socialProfileIdValue: (form)  (optional)
     - parameter appFileContent: (form)  (optional)
     - parameter appFileSha256: (form)  (optional)
     - parameter appFileCreatedAtUtc: (form)  (optional)
     - parameter appFileUserIdValue: (form)  (optional)
     - parameter appFileTenantIdValue: (form)  (optional)
     - parameter appFileEnrollmentIdValue: (form)  (optional)
     - parameter appFileSource: (form)  (optional)
     - parameter appFileLength: (form)  (optional)
     - parameter appFileName: (form)  (optional)
     - parameter appFileFileName: (form)  (optional)
     - parameter appFileLastModified: (form)  (optional)
     - parameter appFileSize: (form)  (optional)
     - parameter appFileContentType: (form)  (optional)
     - parameter appFileContentDisposition: (form)  (optional)
     - parameter appFileHeaders: (form)  (optional)
     - parameter id: (form)  (optional)
     - parameter timestamp: (form)  (optional)
     - returns: RequestBuilder<EmptyEnvelope> 
     */
    open class func saveFileAsyncWithRequestBuilder(tenantId: UUID? = nil, apiVersion: String? = nil, xApiVersion: String? = nil, file: URL? = nil, notes: String? = nil, title: String? = nil, author: String? = nil, isFolder: Bool? = nil, fileName: String? = nil, abstract: String? = nil, keyWords: String? = nil, validResponse: Bool? = nil, parentFileUploadId: String? = nil, filePath: String? = nil, publicAccessType: PublicAccessType_saveFileAsync? = nil, purpose: Purpose_saveFileAsync? = nil, socialProfileIdValue: UUID? = nil, appFileContent: Data? = nil, appFileSha256: String? = nil, appFileCreatedAtUtc: Date? = nil, appFileUserIdValue: UUID? = nil, appFileTenantIdValue: UUID? = nil, appFileEnrollmentIdValue: UUID? = nil, appFileSource: AppFileSource_saveFileAsync? = nil, appFileLength: Int64? = nil, appFileName: String? = nil, appFileFileName: String? = nil, appFileLastModified: Date? = nil, appFileSize: Int64? = nil, appFileContentType: String? = nil, appFileContentDisposition: String? = nil, appFileHeaders: [String: String]? = nil, id: UUID? = nil, timestamp: Date? = nil) -> RequestBuilder<EmptyEnvelope> {
        let localVariablePath = "/api/v2/StorageService/Uploads"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file?.encodeToJSON(),
            "notes": notes?.encodeToJSON(),
            "title": title?.encodeToJSON(),
            "author": author?.encodeToJSON(),
            "isFolder": isFolder?.encodeToJSON(),
            "fileName": fileName?.encodeToJSON(),
            "abstract": abstract?.encodeToJSON(),
            "keyWords": keyWords?.encodeToJSON(),
            "validResponse": validResponse?.encodeToJSON(),
            "parentFileUploadId": parentFileUploadId?.encodeToJSON(),
            "filePath": filePath?.encodeToJSON(),
            "publicAccessType": publicAccessType?.encodeToJSON(),
            "purpose": purpose?.encodeToJSON(),
            "socialProfileId.value": socialProfileIdValue?.encodeToJSON(),
            "appFile.content": appFileContent?.encodeToJSON(),
            "appFile.sha256": appFileSha256?.encodeToJSON(),
            "appFile.createdAtUtc": appFileCreatedAtUtc?.encodeToJSON(),
            "appFile.userId.value": appFileUserIdValue?.encodeToJSON(),
            "appFile.tenantId.value": appFileTenantIdValue?.encodeToJSON(),
            "appFile.enrollmentId.value": appFileEnrollmentIdValue?.encodeToJSON(),
            "appFile.source": appFileSource?.encodeToJSON(),
            "appFile.length": appFileLength?.encodeToJSON(),
            "appFile.name": appFileName?.encodeToJSON(),
            "appFile.fileName": appFileFileName?.encodeToJSON(),
            "appFile.lastModified": appFileLastModified?.encodeToJSON(),
            "appFile.size": appFileSize?.encodeToJSON(),
            "appFile.contentType": appFileContentType?.encodeToJSON(),
            "appFile.contentDisposition": appFileContentDisposition?.encodeToJSON(),
            "appFile.headers": appFileHeaders?.encodeToJSON(),
            "id": id?.encodeToJSON(),
            "timestamp": timestamp?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "tenantId": (wrappedValue: tenantId?.encodeToJSON(), isExplode: true),
            "api-version": (wrappedValue: apiVersion?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
            "x-api-version": xApiVersion?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EmptyEnvelope>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
