//
// ServiceCaseDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceCaseDto: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var title: String?
    public var description: String?
    public var instructions: String?
    public var taxable: Bool?
    public var workLocation: String?
    public var serviceId: String?
    public var serviceQueueId: String?
    public var serviceCaseTypeId: String?
    public var serviceLevelAgreementId: String?
    public var individualId: String?
    public var organizationId: String?
    public var accountHolderId: String?
    public var receiverBusinessId: String?
    public var currencyId: String?
    public var territoryId: String?
    public var priceListId: String?
    public var promisedStartDate: Date?
    public var promisedEndDate: Date?

    public init(id: String? = nil, timestamp: Date? = nil, title: String? = nil, description: String? = nil, instructions: String? = nil, taxable: Bool? = nil, workLocation: String? = nil, serviceId: String? = nil, serviceQueueId: String? = nil, serviceCaseTypeId: String? = nil, serviceLevelAgreementId: String? = nil, individualId: String? = nil, organizationId: String? = nil, accountHolderId: String? = nil, receiverBusinessId: String? = nil, currencyId: String? = nil, territoryId: String? = nil, priceListId: String? = nil, promisedStartDate: Date? = nil, promisedEndDate: Date? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.title = title
        self.description = description
        self.instructions = instructions
        self.taxable = taxable
        self.workLocation = workLocation
        self.serviceId = serviceId
        self.serviceQueueId = serviceQueueId
        self.serviceCaseTypeId = serviceCaseTypeId
        self.serviceLevelAgreementId = serviceLevelAgreementId
        self.individualId = individualId
        self.organizationId = organizationId
        self.accountHolderId = accountHolderId
        self.receiverBusinessId = receiverBusinessId
        self.currencyId = currencyId
        self.territoryId = territoryId
        self.priceListId = priceListId
        self.promisedStartDate = promisedStartDate
        self.promisedEndDate = promisedEndDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case title
        case description
        case instructions
        case taxable
        case workLocation
        case serviceId
        case serviceQueueId
        case serviceCaseTypeId
        case serviceLevelAgreementId
        case individualId
        case organizationId
        case accountHolderId
        case receiverBusinessId
        case currencyId
        case territoryId
        case priceListId
        case promisedStartDate
        case promisedEndDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(instructions, forKey: .instructions)
        try container.encodeIfPresent(taxable, forKey: .taxable)
        try container.encodeIfPresent(workLocation, forKey: .workLocation)
        try container.encodeIfPresent(serviceId, forKey: .serviceId)
        try container.encodeIfPresent(serviceQueueId, forKey: .serviceQueueId)
        try container.encodeIfPresent(serviceCaseTypeId, forKey: .serviceCaseTypeId)
        try container.encodeIfPresent(serviceLevelAgreementId, forKey: .serviceLevelAgreementId)
        try container.encodeIfPresent(individualId, forKey: .individualId)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(accountHolderId, forKey: .accountHolderId)
        try container.encodeIfPresent(receiverBusinessId, forKey: .receiverBusinessId)
        try container.encodeIfPresent(currencyId, forKey: .currencyId)
        try container.encodeIfPresent(territoryId, forKey: .territoryId)
        try container.encodeIfPresent(priceListId, forKey: .priceListId)
        try container.encodeIfPresent(promisedStartDate, forKey: .promisedStartDate)
        try container.encodeIfPresent(promisedEndDate, forKey: .promisedEndDate)
    }
}

