//
// TenantTeamEmployeeEnrollmentCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TenantTeamEmployeeEnrollmentCreateDto: Codable, JSONEncodable, Hashable {

    static let businessTeamIdRule = StringRule(minLength: 36, maxLength: 36, pattern: nil)
    static let employeeProfileIdRule = StringRule(minLength: 36, maxLength: 36, pattern: nil)
    public var id: UUID?
    public var timestamp: Date?
    public var businessTeamId: String
    public var employeeProfileId: String

    public init(id: UUID? = nil, timestamp: Date? = nil, businessTeamId: String, employeeProfileId: String) {
        self.id = id
        self.timestamp = timestamp
        self.businessTeamId = businessTeamId
        self.employeeProfileId = employeeProfileId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case businessTeamId
        case employeeProfileId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encode(businessTeamId, forKey: .businessTeamId)
        try container.encode(employeeProfileId, forKey: .employeeProfileId)
    }
}

