//
// TenantDepartmentUpdateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TenantDepartmentUpdateDto: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var description: String?
    public var disabled: Bool?
    public var businessProfileRecordID: String?
    public var organizationProfileID: String?
    public var parentDepartmentID: String?

    public init(name: String? = nil, description: String? = nil, disabled: Bool? = nil, businessProfileRecordID: String? = nil, organizationProfileID: String? = nil, parentDepartmentID: String? = nil) {
        self.name = name
        self.description = description
        self.disabled = disabled
        self.businessProfileRecordID = businessProfileRecordID
        self.organizationProfileID = organizationProfileID
        self.parentDepartmentID = parentDepartmentID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case disabled
        case businessProfileRecordID
        case organizationProfileID
        case parentDepartmentID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(disabled, forKey: .disabled)
        try container.encodeIfPresent(businessProfileRecordID, forKey: .businessProfileRecordID)
        try container.encodeIfPresent(organizationProfileID, forKey: .organizationProfileID)
        try container.encodeIfPresent(parentDepartmentID, forKey: .parentDepartmentID)
    }
}

