//
// ItemQuestionDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ItemQuestionDto: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var timestamp: Date?
    public var title: String?
    public var needsRevision: Bool?
    public var question: String?
    public var socialProfileID: String?
    public var businessID: String?
    public var itemID: String?

    public init(id: String? = nil, timestamp: Date? = nil, title: String? = nil, needsRevision: Bool? = nil, question: String? = nil, socialProfileID: String? = nil, businessID: String? = nil, itemID: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.title = title
        self.needsRevision = needsRevision
        self.question = question
        self.socialProfileID = socialProfileID
        self.businessID = businessID
        self.itemID = itemID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case title
        case needsRevision
        case question
        case socialProfileID
        case businessID
        case itemID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(needsRevision, forKey: .needsRevision)
        try container.encodeIfPresent(question, forKey: .question)
        try container.encodeIfPresent(socialProfileID, forKey: .socialProfileID)
        try container.encodeIfPresent(businessID, forKey: .businessID)
        try container.encodeIfPresent(itemID, forKey: .itemID)
    }
}

