//
// StoreDataRetentionPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StoreDataRetentionPolicy: Codable, JSONEncodable, Hashable {

    public enum RetentionTimeSpan: String, Codable, CaseIterable {
        case days = "Days"
        case weeks = "Weeks"
        case months = "Months"
        case years = "Years"
    }
    public var dataRetentionTimeSpanAmmount: Int?
    public var retentionTimeSpan: RetentionTimeSpan?

    public init(dataRetentionTimeSpanAmmount: Int? = nil, retentionTimeSpan: RetentionTimeSpan? = nil) {
        self.dataRetentionTimeSpanAmmount = dataRetentionTimeSpanAmmount
        self.retentionTimeSpan = retentionTimeSpan
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataRetentionTimeSpanAmmount
        case retentionTimeSpan
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(dataRetentionTimeSpanAmmount, forKey: .dataRetentionTimeSpanAmmount)
        try container.encodeIfPresent(retentionTimeSpan, forKey: .retentionTimeSpan)
    }
}

