//
// WebPortalCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebPortalCreateDto: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var timestamp: Date?
    public var root: Bool?
    public var title: String?
    public var domain: String?
    public var disabled: Bool?
    public var description: String?
    public var websiteThemeID: String?
    public var businessDomainID: String?
    public var businessPortalApplicationID: String?

    public init(id: UUID? = nil, timestamp: Date? = nil, root: Bool? = nil, title: String? = nil, domain: String? = nil, disabled: Bool? = nil, description: String? = nil, websiteThemeID: String? = nil, businessDomainID: String? = nil, businessPortalApplicationID: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.root = root
        self.title = title
        self.domain = domain
        self.disabled = disabled
        self.description = description
        self.websiteThemeID = websiteThemeID
        self.businessDomainID = businessDomainID
        self.businessPortalApplicationID = businessPortalApplicationID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case root
        case title
        case domain
        case disabled
        case description
        case websiteThemeID
        case businessDomainID
        case businessPortalApplicationID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(root, forKey: .root)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(disabled, forKey: .disabled)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(websiteThemeID, forKey: .websiteThemeID)
        try container.encodeIfPresent(businessDomainID, forKey: .businessDomainID)
        try container.encodeIfPresent(businessPortalApplicationID, forKey: .businessPortalApplicationID)
    }
}

