//
// AssetCategoryCreateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AssetCategoryCreateDto: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var timestamp: Date?
    public var businessId: String?
    public var businessProfileRecordId: String?
    public var name: String?
    public var description: String?

    public init(id: UUID? = nil, timestamp: Date? = nil, businessId: String? = nil, businessProfileRecordId: String? = nil, name: String? = nil, description: String? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.businessId = businessId
        self.businessProfileRecordId = businessProfileRecordId
        self.name = name
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case timestamp
        case businessId
        case businessProfileRecordId
        case name
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(businessId, forKey: .businessId)
        try container.encodeIfPresent(businessProfileRecordId, forKey: .businessProfileRecordId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

