//
// UserAdminDetailDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserAdminDetailDto: Codable, JSONEncodable, Hashable {

    public var orders: [UserOrderSummaryDto]?
    public var logins: [UserExternalLoginDto]?
    public var enrollment: TenantEnrollmentDto?
    public var grantedRoles: [SecurityRoleDto]?
    public var grantedPermissions: [SecurityPermissionDto]?
    public var roleCatalog: [SecurityRoleDto]?
    public var permissionCatalog: [SecurityPermissionDto]?

    public init(orders: [UserOrderSummaryDto]? = nil, logins: [UserExternalLoginDto]? = nil, enrollment: TenantEnrollmentDto? = nil, grantedRoles: [SecurityRoleDto]? = nil, grantedPermissions: [SecurityPermissionDto]? = nil, roleCatalog: [SecurityRoleDto]? = nil, permissionCatalog: [SecurityPermissionDto]? = nil) {
        self.orders = orders
        self.logins = logins
        self.enrollment = enrollment
        self.grantedRoles = grantedRoles
        self.grantedPermissions = grantedPermissions
        self.roleCatalog = roleCatalog
        self.permissionCatalog = permissionCatalog
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orders
        case logins
        case enrollment
        case grantedRoles
        case grantedPermissions
        case roleCatalog
        case permissionCatalog
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orders, forKey: .orders)
        try container.encodeIfPresent(logins, forKey: .logins)
        try container.encodeIfPresent(enrollment, forKey: .enrollment)
        try container.encodeIfPresent(grantedRoles, forKey: .grantedRoles)
        try container.encodeIfPresent(grantedPermissions, forKey: .grantedPermissions)
        try container.encodeIfPresent(roleCatalog, forKey: .roleCatalog)
        try container.encodeIfPresent(permissionCatalog, forKey: .permissionCatalog)
    }
}

