//
// EventInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EventInfo: Codable, JSONEncodable, Hashable {

    public enum MemberType: String, Codable, CaseIterable {
        case constructor = "Constructor"
        case event = "Event"
        case field = "Field"
        case method = "Method"
        case property = "Property"
        case typeInfo = "TypeInfo"
        case custom = "Custom"
        case nestedType = "NestedType"
        case all = "All"
    }
    public enum Attributes: String, Codable, CaseIterable {
        case _none = "None"
        case specialName = "SpecialName"
        case rtspecialname = "RTSpecialName"
    }
    public var name: String?
    public var declaringType: ModelType?
    public var reflectedType: ModelType?
    public var module: Module?
    public var customAttributes: [CustomAttributeData]?
    public var isCollectible: Bool?
    public var metadataToken: Int?
    public var memberType: MemberType?
    public var attributes: Attributes?
    public var isSpecialName: Bool?
    public var addMethod: MethodInfo?
    public var removeMethod: MethodInfo?
    public var raiseMethod: MethodInfo?
    public var isMulticast: Bool?
    public var eventHandlerType: ModelType?

    public init(name: String? = nil, declaringType: ModelType? = nil, reflectedType: ModelType? = nil, module: Module? = nil, customAttributes: [CustomAttributeData]? = nil, isCollectible: Bool? = nil, metadataToken: Int? = nil, memberType: MemberType? = nil, attributes: Attributes? = nil, isSpecialName: Bool? = nil, addMethod: MethodInfo? = nil, removeMethod: MethodInfo? = nil, raiseMethod: MethodInfo? = nil, isMulticast: Bool? = nil, eventHandlerType: ModelType? = nil) {
        self.name = name
        self.declaringType = declaringType
        self.reflectedType = reflectedType
        self.module = module
        self.customAttributes = customAttributes
        self.isCollectible = isCollectible
        self.metadataToken = metadataToken
        self.memberType = memberType
        self.attributes = attributes
        self.isSpecialName = isSpecialName
        self.addMethod = addMethod
        self.removeMethod = removeMethod
        self.raiseMethod = raiseMethod
        self.isMulticast = isMulticast
        self.eventHandlerType = eventHandlerType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case declaringType
        case reflectedType
        case module
        case customAttributes
        case isCollectible
        case metadataToken
        case memberType
        case attributes
        case isSpecialName
        case addMethod
        case removeMethod
        case raiseMethod
        case isMulticast
        case eventHandlerType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(declaringType, forKey: .declaringType)
        try container.encodeIfPresent(reflectedType, forKey: .reflectedType)
        try container.encodeIfPresent(module, forKey: .module)
        try container.encodeIfPresent(customAttributes, forKey: .customAttributes)
        try container.encodeIfPresent(isCollectible, forKey: .isCollectible)
        try container.encodeIfPresent(metadataToken, forKey: .metadataToken)
        try container.encodeIfPresent(memberType, forKey: .memberType)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(isSpecialName, forKey: .isSpecialName)
        try container.encodeIfPresent(addMethod, forKey: .addMethod)
        try container.encodeIfPresent(removeMethod, forKey: .removeMethod)
        try container.encodeIfPresent(raiseMethod, forKey: .raiseMethod)
        try container.encodeIfPresent(isMulticast, forKey: .isMulticast)
        try container.encodeIfPresent(eventHandlerType, forKey: .eventHandlerType)
    }
}

