//
// OrderByClause.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderByClause: Codable, JSONEncodable, Hashable {

    public enum Direction: String, Codable, CaseIterable {
        case ascending = "Ascending"
        case descending = "Descending"
    }
    public var thenBy: OrderByClause?
    public var expression: SingleValueNode?
    public var direction: Direction?
    public var rangeVariable: RangeVariable?
    public var itemType: IEdmTypeReference?

    public init(thenBy: OrderByClause? = nil, expression: SingleValueNode? = nil, direction: Direction? = nil, rangeVariable: RangeVariable? = nil, itemType: IEdmTypeReference? = nil) {
        self.thenBy = thenBy
        self.expression = expression
        self.direction = direction
        self.rangeVariable = rangeVariable
        self.itemType = itemType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case thenBy
        case expression
        case direction
        case rangeVariable
        case itemType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(thenBy, forKey: .thenBy)
        try container.encodeIfPresent(expression, forKey: .expression)
        try container.encodeIfPresent(direction, forKey: .direction)
        try container.encodeIfPresent(rangeVariable, forKey: .rangeVariable)
        try container.encodeIfPresent(itemType, forKey: .itemType)
    }
}

