//
// ParameterInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParameterInfo: Codable, JSONEncodable, Hashable {

    public enum Attributes: String, Codable, CaseIterable {
        case _none = "None"
        case _in = "In"
        case out = "Out"
        case lcid = "Lcid"
        case retval = "Retval"
        case _optional = "Optional"
        case hasDefault = "HasDefault"
        case hasFieldMarshal = "HasFieldMarshal"
        case reserved3 = "Reserved3"
        case reserved4 = "Reserved4"
        case reservedMask = "ReservedMask"
    }
    public var attributes: Attributes?
    public var member: MemberInfo?
    public var name: String?
    public var parameterType: ModelType?
    public var position: Int?
    public var isIn: Bool?
    public var isLcid: Bool?
    public var isOptional: Bool?
    public var isOut: Bool?
    public var isRetval: Bool?
    public var defaultValue: AnyCodable?
    public var rawDefaultValue: AnyCodable?
    public var hasDefaultValue: Bool?
    public var customAttributes: [CustomAttributeData]?
    public var metadataToken: Int?

    public init(attributes: Attributes? = nil, member: MemberInfo? = nil, name: String? = nil, parameterType: ModelType? = nil, position: Int? = nil, isIn: Bool? = nil, isLcid: Bool? = nil, isOptional: Bool? = nil, isOut: Bool? = nil, isRetval: Bool? = nil, defaultValue: AnyCodable? = nil, rawDefaultValue: AnyCodable? = nil, hasDefaultValue: Bool? = nil, customAttributes: [CustomAttributeData]? = nil, metadataToken: Int? = nil) {
        self.attributes = attributes
        self.member = member
        self.name = name
        self.parameterType = parameterType
        self.position = position
        self.isIn = isIn
        self.isLcid = isLcid
        self.isOptional = isOptional
        self.isOut = isOut
        self.isRetval = isRetval
        self.defaultValue = defaultValue
        self.rawDefaultValue = rawDefaultValue
        self.hasDefaultValue = hasDefaultValue
        self.customAttributes = customAttributes
        self.metadataToken = metadataToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributes
        case member
        case name
        case parameterType
        case position
        case isIn
        case isLcid
        case isOptional
        case isOut
        case isRetval
        case defaultValue
        case rawDefaultValue
        case hasDefaultValue
        case customAttributes
        case metadataToken
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(member, forKey: .member)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(parameterType, forKey: .parameterType)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(isIn, forKey: .isIn)
        try container.encodeIfPresent(isLcid, forKey: .isLcid)
        try container.encodeIfPresent(isOptional, forKey: .isOptional)
        try container.encodeIfPresent(isOut, forKey: .isOut)
        try container.encodeIfPresent(isRetval, forKey: .isRetval)
        try container.encodeIfPresent(defaultValue, forKey: .defaultValue)
        try container.encodeIfPresent(rawDefaultValue, forKey: .rawDefaultValue)
        try container.encodeIfPresent(hasDefaultValue, forKey: .hasDefaultValue)
        try container.encodeIfPresent(customAttributes, forKey: .customAttributes)
        try container.encodeIfPresent(metadataToken, forKey: .metadataToken)
    }
}

