//
// RangeVariable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RangeVariable: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var typeReference: IEdmTypeReference?
    public var kind: Int?

    public init(name: String? = nil, typeReference: IEdmTypeReference? = nil, kind: Int? = nil) {
        self.name = name
        self.typeReference = typeReference
        self.kind = kind
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case typeReference
        case kind
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(typeReference, forKey: .typeReference)
        try container.encodeIfPresent(kind, forKey: .kind)
    }
}

